version: "3.5"

services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo mongo:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s
  dodskrok:
    depends_on: 
      mongo:
        condition: service_healthy

    image: mahaad/dodskrok
    build: .
    ports:
      - 3000:3000
    environment:
      MONGOURI: mongodb://root:example@mongo:27017

